ALTER TABLE evidencia
  ADD COLUMN latitude DOUBLE PRECISION,
  ADD COLUMN longitude DOUBLE PRECISION,
  ADD COLUMN captured_at TIMESTAMPTZ,
  ADD COLUMN origem VARCHAR(10),
  ADD COLUMN cidade VARCHAR(150);
