package com.engseg.dto.response;

import com.engseg.entity.NivelRisco;
import com.engseg.entity.StatusNaoConformidade;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

public record NaoConformidadeResponse(
        UUID id,
        UUID estabelecimentoId,
        String estabelecimentoNome,
        String titulo,
        UUID localizacaoId,
        String localizacaoNome,
        String descricao,
        LocalDateTime dataRegistro,
        String tecnicoNome,
        boolean regraDeOuro,
        int severidade,
        int probabilidade,
        NivelRisco nivelRisco,
        UUID engResponsavelConstrutoraId,
        String engConstruturaNome,
        String engConstrutoraEmail,
        String engConstruturaPerfil,
        UUID engResponsavelVerificacaoId,
        String engVerificacaoNome,
        String engVerificacaoEmail,
        String engVerificacaoPerfil,
        LocalDate dataLimiteResolucao,
        String usuarioCriacaoNome,
        String usuarioCriacaoEmail,
        StatusNaoConformidade status,
        boolean vencida,
        boolean reincidencia,
        UUID ncAnteriorId,
        String ncAnteriorTitulo,
        List<NcResumoResponse> cadeiaReincidencias,
        List<NcResumoResponse> reincidencias,
        String porqueUm,
        String porqueUmResposta,
        String porqueDois,
        String porqueDoisResposta,
        String porqueTres,
        String porqueTresResposta,
        String porqueQuatro,
        String porqueQuatroResposta,
        String porqueCinco,
        String porqueCincoResposta,
        String causaRaiz,
        String descricaoExecucao,
        List<AtividadeResponse> atividades,
        List<HistoricoNcResponse> historico,
        List<InvestigacaoSnapshotResponse> investigacaoSnapshots,
        List<ExecucaoSnapshotResponse> execucaoSnapshots,
        List<DevolutivaResponse> devolutivas,
        List<ExecucaoAcaoResponse> execucoes,
        List<ValidacaoResponse> validacoes,
        List<NormaResponse> normas
) {}
